CREATE TABLE IF NOT EXISTS public.pacientes
(
    id_paciente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    numero_historia_clinica character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    apellido_1 character varying(50) COLLATE pg_catalog."default" NOT NULL,
    apellido_2 character varying(50) COLLATE pg_catalog."default",
    fecha_nacimiento date NOT NULL,
    sexo character(1) COLLATE pg_catalog."default" NOT NULL,
    id_zona integer NOT NULL,
    CONSTRAINT pacientes_pkey PRIMARY KEY (id_paciente),
    CONSTRAINT pacientes_numero_historia_clinica_key UNIQUE (numero_historia_clinica),
    CONSTRAINT fk_paciente_zona FOREIGN KEY (id_zona)
        REFERENCES public.zonas_residencia (id_zona) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT pacientes_sexo_check CHECK (sexo = ANY (ARRAY['M'::bpchar, 'F'::bpchar]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pacientes
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.zonas_residencia
(
    id_zona integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_zona character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT zonas_residencia_pkey PRIMARY KEY (id_zona),
    CONSTRAINT zonas_residencia_nombre_zona_key UNIQUE (nombre_zona)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.zonas_residencia
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.episodios_clinicos
(
    id_episodio integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_paciente integer NOT NULL,
    tipo_episodio character varying(30) COLLATE pg_catalog."default" NOT NULL,
    servicio character varying(50) COLLATE pg_catalog."default" NOT NULL,
    motivo_consulta text COLLATE pg_catalog."default",
    fecha_episodio date,
    CONSTRAINT episodios_clinicos_pkey PRIMARY KEY (id_episodio),
    CONSTRAINT fk_episodio_paciente FOREIGN KEY (id_paciente)
        REFERENCES public.pacientes (id_paciente) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.episodios_clinicos
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.diagnosticos
(
    id_diagnostico integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_episodio integer NOT NULL,
    codigo_cie10 character varying(10) COLLATE pg_catalog."default" NOT NULL,
    descripcion_diagnostico character varying(200) COLLATE pg_catalog."default" NOT NULL,
    tipo_diagnostico character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha_diagnostico date NOT NULL,
    CONSTRAINT diagnosticos_pkey PRIMARY KEY (id_diagnostico),
    CONSTRAINT fk_diagnostico_episodio FOREIGN KEY (id_episodio)
        REFERENCES public.episodios_clinicos (id_episodio) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT diagnosticos_tipo_diagnostico_check CHECK (tipo_diagnostico::text = ANY (ARRAY['principal'::character varying, 'secundario'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.diagnosticos
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.analiticas
(
    id_analitica integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_episodio integer NOT NULL,
    fecha_analitica date NOT NULL,
    glucosa_mg_dl numeric(6,2),
    colesterol_total_mg_dl numeric(6,2),
    hemoglobina_g_dl numeric(5,2),
    CONSTRAINT analiticas_pkey PRIMARY KEY (id_analitica),
    CONSTRAINT fk_analitica_episodio FOREIGN KEY (id_episodio)
        REFERENCES public.episodios_clinicos (id_episodio) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.analiticas
    OWNER to postgres;
