CREATE TABLE IF NOT EXISTS public.investigadores
(
    id_investigador integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    apellido_1 character varying(50) COLLATE pg_catalog."default" NOT NULL,
    apellido_2 character varying(50) COLLATE pg_catalog."default",
    email_institucional character varying(100) COLLATE pg_catalog."default" NOT NULL,
    departamento character varying(100) COLLATE pg_catalog."default" NOT NULL,
    categoria character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT investigadores_pkey PRIMARY KEY (id_investigador),
    CONSTRAINT uq_investigadores_email UNIQUE (email_institucional)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.investigadores
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.admins
(
    id_admin integer NOT NULL DEFAULT nextval('admins_id_admin_seq'::regclass),
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admins_pkey PRIMARY KEY (id_admin),
    CONSTRAINT admins_username_key UNIQUE (username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.admins
    OWNER to postgres;
-- Index: ix_admins_id_admin

-- DROP INDEX IF EXISTS public.ix_admins_id_admin;

CREATE INDEX IF NOT EXISTS ix_admins_id_admin
    ON public.admins USING btree
    (id_admin ASC NULLS LAST)
    TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.tipos_consultas
(
    id_tipo_consulta integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    codigo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    vista_base character varying(100) COLLATE pg_catalog."default" NOT NULL,
    columnas_select jsonb NOT NULL,
    filtros_permitidos jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT tipos_consultas_pkey PRIMARY KEY (id_tipo_consulta),
    CONSTRAINT uq_tipos_consultas_codigo UNIQUE (codigo),
    CONSTRAINT chk_tipos_consultas_columnas_json CHECK (jsonb_typeof(columnas_select) = 'array'::text),
    CONSTRAINT chk_tipos_consultas_filtros_json CHECK (jsonb_typeof(filtros_permitidos) = 'object'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tipos_consultas
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.peticiones
(
    id_peticion integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_investigador integer NOT NULL,
    id_tipo_consulta integer NOT NULL,
    fecha_solicitud timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    descripcion_peticion text COLLATE pg_catalog."default",
    estado_peticion character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'solicitada'::character varying,
    parametros_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT peticiones_pkey PRIMARY KEY (id_peticion),
    CONSTRAINT fk_peticion_investigador FOREIGN KEY (id_investigador)
        REFERENCES public.investigadores (id_investigador) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_peticion_tipo FOREIGN KEY (id_tipo_consulta)
        REFERENCES public.tipos_consultas (id_tipo_consulta) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT chk_estado_peticion CHECK (estado_peticion::text = ANY (ARRAY['solicitada'::character varying, 'ejecutada'::character varying, 'denegada'::character varying]::text[])),
    CONSTRAINT chk_parametros_json CHECK (jsonb_typeof(parametros_json) = 'object'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.peticiones
    OWNER to postgres;
